// app/api/payu/initiate-payment/route.ts

import { NextResponse } from 'next/server';
import crypto from 'crypto';
import { db } from '@/lib/firebase/admin';

const PAYU_KEY = process.env.PAYU_KEY;
const PAYU_SALT = process.env.PAYU_SALT;
const PAYU_BASE_URL = process.env.PAYU_BASE_URL || 'https://test.payu.in/_payment';

export async function POST(request: Request) {
  if (!PAYU_KEY || !PAYU_SALT) {
    console.error('CRITICAL ERROR: PayU credentials (PAYU_KEY, PAYU_SALT) are not configured in environment variables.');
    return NextResponse.json({ message: 'Server configuration error.' }, { status: 500 });
  }

  try {
    console.log('--- PayU Initiate API Call Started ---');

    const {
      amount,
      txnid,
      productinfo,
      firstname,
      email,
      phone,
      surl,
      furl,
      udf1, udf2, udf3, udf4, udf5,
      bookingPayload
    } = await request.json();

    if (!amount || !txnid || !productinfo || !firstname || !email || !phone || !surl || !furl || !bookingPayload) {
      console.error('Validation Error: Missing required payment parameters or booking payload.');
      return NextResponse.json({ message: 'Missing required payment parameters or booking payload.' }, { status: 400 });
    }

    console.log('Attempting to save booking to Firestore using Admin SDK...');
    const bookingRef = db.collection("bookings").doc(txnid);
    
    await bookingRef.set({
        ...bookingPayload,
        payment: {
            ...bookingPayload.payment,
            status: 'pending',
            transactionId: txnid,
            payuPaymentId: '',
            message: 'Payment initiated, awaiting PayU response.'
        },
        createdAt: new Date().toISOString()
    });
    
    console.log('Booking successfully saved to Firestore with pending status.');

    const payuParams = {
      key: PAYU_KEY,
      txnid: txnid,
      amount: parseFloat(amount).toFixed(2),
      productinfo: productinfo,
      firstname: firstname,
      email: email,
      phone: phone,
      surl: surl,
      furl: furl,
      hash: '',
      udf1: String(udf1 || ''),
      udf2: String(udf2 || ''),
      udf3: String(udf3 || ''),
      udf4: String(udf4 || ''),
      udf5: String(udf5 || ''),
    };

    // --- [DEBUGGING STEP] ---
    // The order of fields in this string is CRITICAL.
    const hashString = `${payuParams.key}|${payuParams.txnid}|${payuParams.amount}|${payuParams.productinfo}|${payuParams.firstname}|${payuParams.email}|${payuParams.udf1}|${payuParams.udf2}|${payuParams.udf3}|${payuParams.udf4}|${payuParams.udf5}||||||${PAYU_SALT}`;
    
    // This new log will print the exact string your server is using.
    console.log("--- HASH STRING GENERATED BY YOUR SERVER ---");
    console.log(hashString);
    console.log("-------------------------------------------");
    
    const hash = crypto.createHash('sha512').update(hashString).digest('hex');
    payuParams.hash = hash;

    console.log('Generated Hash:', hash);
    console.log('--- PayU Initiate API Call Finished Successfully ---');

    return NextResponse.json({
      success: true,
      payuParams,
      payuBaseUrl: PAYU_BASE_URL,
      txnid
    });

  } catch (error: any) {
    console.error('Error in /api/payu/initiate-payment:', error);
    return NextResponse.json({ success: false, message: 'An internal server error occurred.' }, { status: 500 });
  }
}
